#!/usr/bin/env python3
"""Generate the license-free ONNX demo model for the W025 plugin PoC.

A 5x5 Gaussian smoothing convolution on a single float32 channel with
dynamic H/W. Trivially verifiable (unit test compares against a JS
reference implementation) and small enough to inline as base64 in the
bundle — it proves the whole ONNX path (lazy ORT load, EP negotiation,
IDB weight cache, tiled execution, overlay) without any license risk.

Run:  tools/venv python tools/make-demo-onnx.py
Emits: src/ml/demo/speckle-smooth-demo.onnx.b64.js
"""
import base64
import os

import numpy as np
import onnx
from onnx import TensorProto, helper

# 5x5 Gaussian kernel, sigma=1.0, normalized
ax = np.arange(-2, 3, dtype=np.float64)
g1 = np.exp(-(ax ** 2) / 2.0)
k = np.outer(g1, g1)
k /= k.sum()
kernel = k.astype(np.float32).reshape(1, 1, 5, 5)

W = helper.make_tensor("W", TensorProto.FLOAT, kernel.shape, kernel.flatten())

node = helper.make_node(
    "Conv", inputs=["input", "W"], outputs=["output"],
    kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1],
)

graph = helper.make_graph(
    [node], "speckle_smooth_demo",
    inputs=[helper.make_tensor_value_info("input", TensorProto.FLOAT, [1, 1, "H", "W"])],
    outputs=[helper.make_tensor_value_info("output", TensorProto.FLOAT, [1, 1, "H", "W"])],
    initializer=[W],
)

model = helper.make_model(
    graph,
    producer_name="sardine-w025",
    opset_imports=[helper.make_opsetid("", 13)],
    ir_version=8,
)

# Deepness-convention metadata_props so the importer path is exercised too
for key, val in {
    "model_type": '"Superresolution"',  # closest Deepness type to enhancement
    "class_names": "null",
    "tiles_size": "256",
    "tiles_overlap": "16",
}.items():
    p = model.metadata_props.add()
    p.key, p.value = key, val

onnx.checker.check_model(model)

raw = model.SerializeToString()
b64 = base64.b64encode(raw).decode("ascii")

out_path = os.path.join(os.path.dirname(__file__), "..", "src", "ml", "demo",
                        "speckle-smooth-demo.onnx.b64.js")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write(
        "// GENERATED by tools/make-demo-onnx.py — do not edit.\n"
        "// 5x5 Gaussian Conv, float32, dynamic H/W, opset 13. License: CC0 (generated).\n"
        f"// {len(raw)} bytes raw.\n"
        f"export const SPECKLE_SMOOTH_DEMO_ONNX_B64 = '{b64}';\n"
    )
print(f"wrote {out_path}: {len(raw)} bytes raw, {len(b64)} chars base64")
